name: 'Assume Digabi AWS Role'

inputs:
  aws-account-id:
        description: 'AWS Account ID to access'
        required: true
runs:
  using: 'composite'
  steps:
    - name: Get repository name
      id: output_repo_name
      uses: digabi/workflows-common/actions/parse-repo-name@use-gh-for-test-images
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ steps.output_repo_name.outputs.repo_name }}-github-access
          aws-region: eu-north-1
          mask-aws-account-id: true
