name: 'Delete image from Github Container Registry with specified tag'

inputs:
  image-tag:
        description: 'Image tag of the image to delete'
        required: true
  image-name:
        description: 'Name of the image (package) to delete from'
  github-token:
        description: 'GitHub token with read and delete package permissions'
        required: true
runs:
  using: 'composite'
  steps:
    - name: Get repository name
      id: output_repo_name
      uses: digabi/workflows-common/actions/parse-repo-name@use-gh-for-test-images
    - name: Delete image with tag ${{ inputs.image-tag }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO_NAME: ${{ inputs.image-name || steps.output_repo_name.outputs.repo_name }}
      run: |
        package_version_id=$(
          gh api /orgs/digabi/packages/container/${{ env.REPO_NAME }}/versions --jq ".[] | select(.metadata.container.tags | index(\"${{ inputs.image-tag }}\")) | .id"
        )

        if [ -z "$package_version_id" ]; then
          echo "No package version found with tag ${{ inputs.image-tag }}"
          exit 0
        fi

        gh api \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/digabi/packages/container/${{ env.REPO_NAME }}/versions/$package_version_id
      shell: bash
