name: "Queue integration test run"

inputs:
  image_tag_latest:
    description: "Docker image tag (branch_latest) that was build in previous step"
    type: string
    required: true
  test_workflow_file:
    description: "Test workflow file name"
    type: string
    required: true
  test_status_name:
    description: "Test status name"
    type: string
    required: true
  cross_repo_access_token:
    description: "Token for cross-repo access"
    type: string
    required: false
runs:
  using: "composite"
  env:
    - TARGET_BRANCH: ${{ github.head_ref || github.ref_name }}
    - INTEGRATION_TESTS_REPO: integration-tests
  steps:
    - id: last-sha
      uses: digabi/workflows-common/actions/last-commit-sha@main

    - name: Mark tests pending
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api repos/${{ github.repository }}/statuses/${{ steps.last-sha.outputs.last_commit_sha }} \
          -F state=pending \
          -F context=${{ inputs.test_status_name }} \
          -F description='Waiting for integration-tests'
      shell: bash

    - name: Check if branch exists in integration-tests repository
      id: check
      run: |
        if gh api repos/${{ env.INTEGRATION_TESTS_REPO }}/branches/${{ env.TARGET_BRANCH }} &>/dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Create branch from master if it doesnt exist
      if: steps.check.outputs.exists == 'false'
      run: |
        master_sha=$(gh api repos/${{ env.INTEGRATION_TESTS_REPO }}/git/ref/heads/master --jq .object.sha)

        gh api \
          -X POST \
          repos/${{ env.INTEGRATION_TESTS_REPO }}/git/refs \
          -f ref="refs/heads/${{ env.TARGET_BRANCH }}" \
          -f sha="$master_sha"

        echo "✅ Branch '${{ env.TARGET_BRANCH }}' created from master"
      shell: bash

    - name: Dispatch test workflow to same branch
      env:
        GH_TOKEN: ${{ inputs.cross_repo_access_token }}
      run: |
        gh workflow run ${{ inputs.test_workflow_file }} \
          -R digabi/integration-tests \
          -r "$TARGET_BRANCH" \
          -F image_tag_latest="${{ inputs.image_tag_latest }}" \
          -F sha="${{ steps.last-sha.outputs.last_commit_sha }}" \
          -F repository="${{ github.repository }}"
      shell: bash
