name: Companion app production release

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      aws-access-role:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      UTILITY_ACCOUNT_ID:
        required: true

jobs:
  release:
    name: Release private image to public ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/${{ inputs.aws-access-role }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Install regctl
        uses: regclient/actions/regctl-installer@ce5fd131e371ffcdd7508b478cb223b3511a9183
        with:
          release: 'v0.7.2'
      - name: Publish prod image
        run: regctl image copy ${{ steps.login-ecr.outputs.registry }}/${{ inputs.app-name }}:${{ inputs.tag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.app-name }}-prod:${{ inputs.tag }}
      - name: Create Github Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          tag_name: ${{ inputs.tag }}
