name: Companion app dev release

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  dev-release:
    name: Release to private ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Assume AWS role
        uses: digabi/workflows-common/actions/assume-digabi-aws-role@main
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.app-name }}:${{ github.ref_name }}
          provenance: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
