name: Companion app production release

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      aws-access-role:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      UTILITY_ACCOUNT_ID:
        required: true

jobs:
  dev-release:
    name: Release to private ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/${{ inputs.aws-access-role }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.app-name }}-prod:${{ github.ref_name }}
          provenance: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
